services:
  frontend:
    build:
      context: .
      dockerfile: configs/vite/Dockerfile

  backend:
    build:
      context: .
      dockerfile: configs/php-fpm/Dockerfile
    volumes:
      - ./symfony:/var/www/symfony

  web:
    image: nginx:stable
    volumes:
      - ./configs/nginx/symfony.nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9580:80"
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
