services:
  frontend:
    build:
      context: .
      dockerfile: ./configs/vite/Dockerfile

  backend:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./express:/app
    command: sh -c "npm install && node server.js"

  web:
    image: nginx:alpine
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9580:80"
    depends_on:
      - vite
      - express
